crate_id: 1
device_configs:
- $OCS_CONFIG_DIR/dev_cfg.yml
docker_env:
  ATCA_MONITOR_TAG: R1.0.0
  CB_HOST: 192.168.0.120
  PYSMURF_CLIENT_TAG: v4.0.0-rc21
  SOCS_TAG: v0.0.1-56-gc58c835
  STREAMER_TAG: v0.0.1-rc21
max_fan_level: 10
pysmurf_configs:
- $OCS_CONFIG_DIR/pysmurf.cfg
shelf_manager: shm-smrf-sp01
smurf_slots:
- 2
startup:
  configure_pysmurf: true
  reboot: true
  set_crate_fans_to_full: true
streamer_ports:
- 4532
- 4533
- 4534
- 4535
- 4536
- 4537
