# Experiment-wide configurations
experiment:
  amp_50k_Vg: -0.6 #Volts
  amp_50k_Id: 15 #mA
  amp_hemt_Vg: -1.1 #Volts
  amp_hemt_Id: 8 #mA
  tunefile: NULL

# Bias group configurations
bias_groups:
  enabled: [1,1,1,1,1,1,1,1,1,1,1,1] #Indicates whether bias group is on [0-11]
  bias_high: [10,10,10,10,10,10,10,10,10,10,10,10] #Volts
  bias_low: [0,0,0,0,0,0,0,0,0,0,0,0] #Volts
  overbias_amp: [19.9,19.9,19.9,19.9,19.9,19.9,19.9,19.9,19.9,19.9,19.9,19.9] #Volts
  bias_step: [0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025] #Volts
  wait_time: [0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001] #Wait time between steps
  ob_wait_time: [30,30,30,30,30,30,30,30,30,30,30,30] #Time to wait after overbiasing bolometers

bands:
  AMC[0]:
    # Power
    uc_att: [30, 30, 30, 30]
    dc_att: [0, 0, 0, 0]
    drive: [12, 12, 12, 12]

    # Tracking
    frac_pp: [0.5, 0.5, 0.5, 0.5]
    flux_ramp_rate_khz: [4, 4, 4, 4]
    lms_freq_hz: [NULL, NULL, NULL, NULL]
    lms_gain: [6, 6, 6, 6]
    feedback_start_frac: [0.25, 0.25, 0.25, 0.25]
    feedback_end_frac: [0.98, 0.98, 0.98, 0.98]
    meas_lms_freq: [True, True, True, True]

    # Should these be here?
    make_plot: [True, True, True, True]
    show_plot: [False, False, False, False]

    # Noise options
    noise_time: [30,30,30,30]
    nperseg: [2**16,2**16,2**16,2**16]

  AMC[1]:
#    power:
    uc_att: [30,30,30,30]
    dc_att: [0,0,0,0]
    drive: [12,12,12,12]
#    tracking:
    frac_pp: [0.5,0.5,0.5,0.5]
    flux_ramp_rate_khz: [4,4,4,4]
    lms_freq_hz: [NULL,NULL,NULL,NULL]
    lms_gain: [6,6,6,6]
    feedback_start_frac: [0.25,0.25,0.25,0.25]
    feedback_end_frac: [0.98,0.98,0.98,0.98]
    meas_lms_freq: [True,True,True,True]
    make_plot: [True,True,True,True]
    show_plot: [False,False,False,False]
#    noise:
    time: [30,30,30,30]
    nperseg: [2**16,2**16,2**16,2**16]

