name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "docs/"
        pre-build-command: "pip3 install -r docs/requirements.txt ."
        build-command: "make html"

    - name: Deploy HTML
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: docs/_build/html/
        remote_path: /mnt/so1/html/github-actions/sodetlib/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}
